import { StyleSheet } from 'react-native';
import { THEME } from '@/constants/theme';

export const hoyTasksSectionStyles = StyleSheet.create({
  agregarMasHint: {
    ...THEME.typography.small,
    fontSize: 13,
    color: THEME.colors.gradient.blue,
    fontFamily: THEME.fonts.heading.medium,
  },
  agregarMasWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    gap: THEME.spacing.xs,
    marginTop: THEME.spacing.sm,
    marginBottom: THEME.spacing.xs,
    paddingVertical: 10,
    paddingHorizontal: THEME.spacing.md,
    backgroundColor: THEME.colors.tint.blue.veryFaint,
    borderRadius: THEME.borderRadius.pill,
    borderWidth: 1,
    borderColor: THEME.colors.tint.blue.border,
  },
  areaCard: {
    marginBottom: THEME.spacing.sm,
    backgroundColor: THEME.colors.fill[100],
    borderRadius: THEME.borderRadius.rounded,
    overflow: 'hidden',
    ...THEME.shadows.card,
  },
  areaCardInner: {
    paddingTop: THEME.spacing.xs,
    paddingBottom: THEME.spacing.xs,
    paddingLeft: 0,
    paddingRight: 0,
  },
  byProjectColorBar: {
    width: 4,
    height: '100%',
    minHeight: 36,
    borderTopLeftRadius: 2,
    borderBottomLeftRadius: 2,
    marginRight: THEME.spacing.sm,
  },
  byProjectHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: THEME.spacing.sm,
    gap: THEME.spacing.sm,
  },
  byProjectHeaderIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: THEME.colors.tint.blue.veryFaint,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: THEME.spacing.sm,
  },
  byProjectHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
  },
  byProjectList: {
    gap: THEME.spacing.xs,
  },
  byProjectLooseList: {
    marginBottom: THEME.spacing.sm,
    paddingLeft: THEME.spacing.xs,
  },
  byProjectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: THEME.colors.fill[200],
    borderRadius: THEME.borderRadius.standard,
    paddingVertical: THEME.spacing.sm,
    paddingRight: THEME.spacing.sm,
    marginBottom: THEME.spacing.xs,
  },
  byProjectRowContent: {
    flex: 1,
    minWidth: 0,
  },
  byProjectRowCount: {
    ...THEME.typography.small,
    color: THEME.colors.text.secondary,
    marginTop: 2,
  },
  byProjectRowLoose: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: THEME.colors.fill[200],
    borderRadius: THEME.borderRadius.standard,
    paddingVertical: THEME.spacing.sm,
    paddingRight: THEME.spacing.sm,
    marginBottom: THEME.spacing.xs,
  },
  byProjectRowName: {
    ...THEME.typography.body,
    fontFamily: THEME.fonts.heading.medium,
    color: THEME.colors.text.main,
  },
  byProjectSection: {
    marginTop: THEME.spacing.xs,
    marginBottom: THEME.spacing.sm,
    paddingTop: THEME.spacing.sm,
    borderTopWidth: 1,
    borderTopColor: THEME.colors.stroke[100],
  },
  byProjectTitle: {
    ...THEME.typography.caption,
    fontFamily: THEME.fonts.heading.bold,
    color: THEME.colors.text.main,
    flexShrink: 1,
  },
  byProjectVerTodosHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 0,
    paddingVertical: THEME.spacing.xs,
  },
  byProjectVerTodosText: {
    ...THEME.typography.small,
    fontFamily: THEME.fonts.heading.medium,
    color: THEME.colors.gradient.blue,
    marginRight: 4,
  },
  categoryLabelChevron: {
    flexShrink: 0,
  },
  categoryLabelCount: {
    ...THEME.typography.caption,
    fontSize: 13,
    color: THEME.colors.text.secondary,
    fontFamily: THEME.fonts.heading.medium,
  },
  categoryLabelName: {
    fontSize: 18,
    fontFamily: THEME.fonts.heading.bold,
    color: THEME.colors.text.main,
    letterSpacing: 0.2,
  },
  categoryLabelRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing.sm,
  },
  categoryLabelStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: THEME.spacing.sm,
    paddingHorizontal: THEME.spacing.md,
    borderLeftWidth: 4,
    backgroundColor: THEME.colors.fill[200],
  },
  checkInPromptBanner: {
    marginBottom: THEME.spacing.md,
    borderRadius: THEME.borderRadius.rounded,
    overflow: 'hidden',
    ...THEME.shadows.soft,
  },
  checkInPromptBannerGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: THEME.spacing.md,
    paddingHorizontal: THEME.spacing.md,
    gap: THEME.spacing.sm,
  },
  checkInPromptBannerSub: {
    ...THEME.typography.small,
    color: THEME.colors.text.secondary,
    lineHeight: 20,
  },
  checkInPromptBannerTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  checkInPromptBannerTitle: {
    ...THEME.typography.body,
    fontFamily: THEME.fonts.heading.bold,
    color: THEME.colors.text.main,
    marginBottom: 4,
  },
  emotionalCardAnimatedWrap: {
    marginTop: THEME.spacing.xs,
  },
  emotionalClosureCard: {
    marginTop: THEME.spacing.xs,
    borderRadius: THEME.borderRadius.standard,
    borderWidth: 1,
    borderColor: THEME.colors.fill[200],
    paddingVertical: THEME.spacing.xs,
    paddingHorizontal: THEME.spacing.sm,
    overflow: 'hidden',
  },
  emotionalClosureHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  emotionalClosureMessage: {
    ...THEME.typography.body,
    color: THEME.colors.text.main,
    fontSize: 14,
    lineHeight: 21,
  },
  emotionalClosureNote: {
    ...THEME.typography.small,
    color: THEME.colors.text.secondary,
    lineHeight: 18,
    flex: 1,
  },
  emotionalClosureTitle: {
    fontSize: 12,
    fontFamily: THEME.fonts.heading.bold,
    color: THEME.colors.text.secondary,
    letterSpacing: 0.2,
  },
  emotionalMemoryBadge: {
    backgroundColor: THEME.colors.tint.pink.soft,
  },
  emotionalMemoryCard: {
    marginBottom: THEME.spacing.xs,
    borderRadius: THEME.borderRadius.standard,
    borderWidth: 1,
    borderColor: THEME.colors.fill[200],
    paddingVertical: THEME.spacing.xs,
    paddingHorizontal: THEME.spacing.sm,
    overflow: 'hidden',
  },
  emotionalMemoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  emotionalMemoryMessage: {
    ...THEME.typography.body,
    color: THEME.colors.text.main,
    fontSize: 14,
    lineHeight: 21,
  },
  emotionalMemoryTip: {
    ...THEME.typography.small,
    color: THEME.colors.text.secondary,
    lineHeight: 18,
    flex: 1,
  },
  emotionalMemoryTitle: {
    fontSize: 12,
    fontFamily: THEME.fonts.heading.bold,
    color: THEME.colors.text.secondary,
    letterSpacing: 0.2,
  },
  emotionalSignalBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: THEME.borderRadius.pill,
    backgroundColor: THEME.colors.fill[100],
    borderWidth: 1,
    borderColor: THEME.colors.fill[200],
  },
  emotionalSignalBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  emotionalSignalBadgeText: {
    ...THEME.typography.meta,
    color: THEME.colors.text.secondary,
    fontFamily: THEME.fonts.heading.bold,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  emotionalSignalDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: THEME.colors.gradient.blue,
    opacity: 0.65,
  },
  emotionalSignalTipRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    marginTop: 4,
  },
  emotionalToneLine: {
    ...THEME.typography.small,
    color: THEME.colors.text.tertiary,
    marginTop: 6,
    fontStyle: 'italic',
    lineHeight: 17,
  },
  emptyTasksActions: {
    marginTop: THEME.spacing.sm,
    width: '100%',
    alignItems: 'center',
  },
  emptyTasksCta: {
    marginTop: THEME.spacing.md,
    width: '100%',
    maxWidth: 280,
    gap: THEME.spacing.sm,
    alignItems: 'center',
  },
  emptyTasksIcon: {
    marginBottom: THEME.spacing.sm,
  },
  emptyTasksInCard: {
    paddingVertical: THEME.spacing.lg,
    paddingHorizontal: THEME.spacing.sm,
    alignItems: 'center',
  },
  emptyTasksInCardText: {
    ...THEME.typography.body,
    color: THEME.colors.text.secondary,
    textAlign: 'center',
    maxWidth: 320,
  },
  emptyTasksLinkPill: {
    paddingVertical: 10,
    paddingHorizontal: THEME.spacing.md,
    borderRadius: THEME.borderRadius.pill,
    backgroundColor: THEME.colors.fill[200],
    borderWidth: 1,
    borderColor: THEME.colors.stroke[100],
  },
  emptyTasksLinkPillSecond: {
    marginTop: THEME.spacing.sm,
  },
  emptyTasksLinkPillText: {
    ...THEME.typography.small,
    fontSize: 14,
    fontFamily: THEME.fonts.heading.medium,
    color: THEME.colors.text.main,
  },
  emptyTasksSecondaryCta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: THEME.spacing.xs,
    paddingVertical: THEME.spacing.sm,
  },
  emptyTasksSecondaryCtaText: {
    ...THEME.typography.body,
    fontFamily: THEME.fonts.heading.medium,
    color: THEME.colors.gradient.blue,
  },
  emptyTasksTitle: {
    ...THEME.typography.h3,
    fontSize: 18,
    color: THEME.colors.text.main,
    fontFamily: THEME.fonts.heading.bold,
    textAlign: 'center',
    marginBottom: THEME.spacing.xs,
  },
  heroDetailsExpandedBody: {
    gap: THEME.spacing.sm,
    marginTop: THEME.spacing.xs,
  },
  heroDetailsSectionLabel: {
    ...THEME.typography.meta,
    fontFamily: THEME.fonts.heading.bold,
    color: THEME.colors.text.tertiary,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  heroDetailsToggleTitle: {
    flex: 1,
    fontSize: 13,
    fontFamily: THEME.fonts.heading.bold,
    color: THEME.colors.text.secondary,
    letterSpacing: 0.2,
  },
  heroTodayWrap: {
    marginTop: THEME.spacing.xs,
    marginBottom: THEME.spacing.sm,
  },
  heroTodayWrapFirst: {
    marginTop: 0,
  },
  prioritiesContext: {
    marginTop: THEME.spacing.md,
    paddingTop: THEME.spacing.sm,
    marginBottom: THEME.spacing.xs,
    borderTopWidth: 1,
    borderTopColor: THEME.colors.fill[200],
  },
  prioritiesContextHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: THEME.spacing.xs,
  },
  prioritiesContextText: {
    ...THEME.typography.body,
    color: THEME.colors.text.main,
    fontSize: 15,
    lineHeight: 23,
    marginBottom: 2,
  },
  prioritiesContextUnderHero: {
    marginTop: THEME.spacing.sm,
    paddingTop: THEME.spacing.sm,
  },
  prioritiesSuggestion: {
    ...THEME.typography.body,
    color: THEME.colors.text.main,
    fontFamily: THEME.fonts.heading.medium,
    fontSize: 13,
    flex: 1,
    lineHeight: 20,
  },
  prioritiesSuggestionBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: THEME.spacing.sm,
    backgroundColor: THEME.colors.gradient.blue + '0C',
    borderRadius: THEME.borderRadius.standard,
    padding: THEME.spacing.sm,
    marginTop: THEME.spacing.sm,
    borderLeftWidth: 4,
    borderLeftColor: THEME.colors.gradient.blue,
  },
  prioritizeHowBullet: {
    ...THEME.typography.caption,
    color: THEME.colors.text.secondary,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 8,
  },
  prioritizeHowList: {
    marginTop: THEME.spacing.xs,
    paddingBottom: THEME.spacing.xs,
  },
  redistributeCta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: THEME.spacing.sm,
    marginTop: THEME.spacing.sm,
    paddingVertical: THEME.spacing.sm,
    paddingHorizontal: THEME.spacing.md,
    backgroundColor: THEME.colors.tint.blue.veryLight,
    borderRadius: THEME.borderRadius.rounded,
    borderWidth: 1,
    borderColor: THEME.colors.tint.blue.border,
  },
  redistributeCtaSub: {
    ...THEME.typography.caption,
    color: THEME.colors.text.secondary,
    marginTop: 2,
    lineHeight: 18,
  },
  redistributeCtaTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  redistributeCtaTitle: {
    ...THEME.typography.body,
    fontFamily: THEME.fonts.heading.bold,
    color: THEME.colors.text.main,
    fontSize: 15,
  },
  tareasDate: {
    ...THEME.typography.small,
    color: THEME.colors.text.secondary,
    flexShrink: 0,
  },
  tareasHeaderMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: THEME.spacing.sm,
    marginTop: THEME.spacing.xs,
  },
  tareasHeaderSection: {
    marginBottom: THEME.spacing.sm,
    paddingBottom: THEME.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: THEME.colors.stroke[100],
  },
  tareasSubtitle: {
    ...THEME.typography.small,
    color: THEME.colors.text.secondary,
    marginTop: 6,
    fontSize: 13,
    lineHeight: 18,
    width: '100%',
  },
  tareasTitle: {
    ...THEME.typography.h2,
    fontSize: 24,
    lineHeight: 30,
    color: THEME.colors.text.main,
    fontFamily: THEME.fonts.heading.bold,
  },
  taskCompactHint: {
    ...THEME.typography.meta,
    lineHeight: 16,
    color: THEME.colors.text.tertiary,
    marginTop: 6,
    width: '100%',
  },
  taskFilterHint: {
    ...THEME.typography.small,
    fontSize: 12,
    color: THEME.colors.text.tertiary,
    marginTop: 4,
    marginBottom: 0,
    width: '100%',
  },
  taskFilterLabel: {
    ...THEME.typography.body,
    fontSize: 14,
    color: THEME.colors.text.secondary,
    fontFamily: THEME.fonts.heading.medium,
    zIndex: 1,
  },
  taskFilterLabelActive: {
    color: THEME.colors.onGradient,
    fontFamily: THEME.fonts.heading.bold,
  },
  taskFilterPill: {
    paddingVertical: 8,
    paddingHorizontal: THEME.spacing.sm,
    borderRadius: THEME.borderRadius.pill,
    backgroundColor: THEME.colors.fill[200],
    minWidth: 88,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  taskFilterPillActive: {
    backgroundColor: 'transparent',
  },
  taskFilterWrap: {
    flexDirection: 'row',
    gap: THEME.spacing.xs,
    flexShrink: 0,
    alignItems: 'center',
  },
  tasksContainer: {
    paddingHorizontal: THEME.spacing.lg,
    paddingBottom: THEME.spacing.sm,
  },
  tasksListCard: {
    backgroundColor: THEME.colors.fill[100],
    borderRadius: THEME.borderRadius.rounded,
    padding: THEME.spacing.md,
    marginBottom: THEME.spacing.sm,
    borderWidth: 1,
    borderColor: THEME.colors.stroke[100],
    ...THEME.shadows.card,
  },
});
